version: "3.8"
services:
  pharmacy-recommend-redis:
    container_name: pharmacy-recommend-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: iamhyeok/pharmacy-recommend-redis # 도커 이미지명을 지을때는 도커 허브에 push할 때 어떤 repository로 push해야하는지 찾지 못하기 때문에 도커 허브 아이디가 먼저 명시가 되어야한다.
    ports:
      - "6379:6379"
  pharmacy-recommend-database:
    container_name: pharmacy-recommend-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: iamhyeok/pharmacy-recommend-database # 도커 이미지명을 지을때는 도커 허브에 push할 때 어떤 repository로 push해야하는지 찾지 못하기 때문에 도커 허브 아이디가 먼저 명시가 되어야한다.
    environment:
      - MARIADB_DATABASE=pharmacy-recommend
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"